version: '3'

services:
  python:
    build: ./python
    tty: true
    volumes:
      - ./python/src:/app/py/src
      - ./python/data:/app/py/data
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
